name: 'issue-status-labeler'
description: 'Updates status label based on a comment'
inputs:
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
    required: true

  labels:
    description: comma delimited list of valid status labels
    default: green, yellow, red
    required: true
  
  colors:
    description: valid colors
    default: 22a524, fbca04, b60205
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'